- name: Preparing Java 8 repo
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept Java 8 license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Update apt caches
  apt: update_cache=yes

- name: Install Java 8
  apt: name=oracle-java8-installer state=present

#- name: Ensure that Apache web server is installed
#  apt: name=apache2 state=present

#- name: Ensure that the service is running and persistent
#  service: name=apache2 state=started enabled=yes